#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: com.exampl
#  redis:
#    host: ${SPRING_REDIS_HOST}
#    port: ${SPRING_REDIS_PORT}
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
jwt:
  secret: askjfhgp9eglifslkhfdsfg5w434gelifbhqwajskhfg8o723goagvfrlouq2ygelifvwaifveliwyafrdeukajvgvlo8fc
  access: 86400
  refresh: 2592000
server:
  port: 18501